[build-system]
requires = ["scikit-build-core>=0.9", "nanobind"]
build-backend = "scikit_build_core.build"

[project]
name = "bagz"
description="A format for storing a sequence of byte-array records"
license = {file = "LICENSE"}
authors = [
    { name = "Charlie Beattie", email = "cbeattie@google.com" },
    { name = "Augustin Žídek", email = "augustinzidek@google.com" },
    { name = "Nicolas Porcel", email = "nicolasporcel@google.com" },
]
readme = "README.md"
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering",
]

dynamic = ["version"]

[project.optional-dependencies]
GCS = ["bagz-gcs"]

[project.urls]
"Homepage" = "https://github.com/google-deepmind/bagz"
"Bug Tracker" = "https://github.com/google-deepmind/bagz/issues"

[[tool.dynamic-metadata]]
provider = "scikit_build_core.metadata.setuptools_scm"

[tool.scikit-build]
wheel.py-api = "cp312"
cmake.args = ["-Wno-dev", "-DENABLE_GCS=OFF"]

[tool.setuptools_scm]
fallback_version = "2.0.0"

[tool.cibuildwheel]
manylinux-x86_64-image = "quay.io/pypa/manylinux_2_28_x86_64:2024.12.16-1"
archs = ["auto64"]
build = [
    "cp310-*",
    "cp311-*",
    "cp312-*",
]
build-frontend = "build[uv]"
build-verbosity = 1
test-command = "pytest {package}/src"
test-requires = "pytest absl-py numpy"

[tool.cibuildwheel.environment]
TEST_TMPDIR = "${PWD}/test_tmpdir"

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair --strip -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "11.0"

[tool.uv.sources]
bagz-gcs = { path = "plugins/gcs" }
